"""Skills page — skill registry browser and AutoSkill demo."""

import json
import streamlit as st
from interfaces.dashboard.helpers import run_async

st.set_page_config(page_title="SpineAgent — Skills", page_icon="🧠", layout="wide")

st.title("🧠 Skill Registry")
st.markdown("All capabilities the agent can execute — including AI-generated skills.")

# ── Load skills ──────────────────────────────────────────────────────────────
from skills.registry import SkillRegistry

registry = SkillRegistry()
run_async(registry.ensure_builtin_skills())
all_skills = run_async(registry.list_all())

# ── KPIs ─────────────────────────────────────────────────────────────────────
k1, k2, k3, k4 = st.columns(4)
k1.metric("Total Skills", len(all_skills))
domains = set(s["domain"] for s in all_skills)
k2.metric("Domains", len(domains))
total_usage = sum(s.get("usage_count", 0) for s in all_skills)
k3.metric("Total Executions", total_usage)
auto_count = sum(1 for s in all_skills if s.get("trigger_type") == "auto_generated")
k4.metric("AutoGenerated", auto_count)

st.divider()

# ── Skill catalog ────────────────────────────────────────────────────────────
st.markdown("### Skill Catalog")

# Group by domain
for domain in sorted(domains):
    domain_skills = [s for s in all_skills if s["domain"] == domain]
    domain_emoji = {"sales": "🛒", "production": "🏭", "purchasing": "📦", "person": "👤"}.get(domain, "🔧")

    with st.expander(f"{domain_emoji} **{domain.title()}** — {len(domain_skills)} skill(s)", expanded=True):
        for skill in domain_skills:
            cols = st.columns([3, 1, 1])
            cols[0].markdown(f"**`{skill['name']}`** — {skill['description']}")
            cols[1].markdown(f"Used: **{skill.get('usage_count', 0)}** times")
            trigger = skill.get("trigger_type", "on_demand")
            if trigger == "auto_generated":
                cols[2].markdown("🤖 *AutoGenerated*")
            elif trigger == "persistent":
                cols[2].markdown("🔄 *Persistent*")
            else:
                cols[2].markdown("▶️ *On Demand*")

st.divider()

# ── Skill executor ───────────────────────────────────────────────────────────
st.markdown("### Skill Executor")
st.markdown("Run any skill directly with custom parameters.")

skill_names = [s["name"] for s in all_skills]
selected = st.selectbox("Select Skill", skill_names)

col_param, col_run = st.columns([3, 1])
with col_param:
    order_id = st.number_input("order_id", min_value=1, value=43659, step=1)
    product_id = st.number_input("product_id (optional)", min_value=0, value=0, step=1)

with col_run:
    st.markdown("")
    st.markdown("")
    execute_btn = st.button("▶️ Execute", use_container_width=True)

if execute_btn:
    skill = run_async(registry.get(selected))
    if skill:
        params = {"order_id": int(order_id)}
        if product_id > 0:
            params["product_id"] = int(product_id)

        with st.spinner(f"Executing `{selected}`..."):
            try:
                result = run_async(skill.execute(**params))
                run_async(registry.record_usage(selected))
            except Exception as e:
                result = {"success": False, "error": str(e)}

        if result.get("success"):
            st.success(f"`{selected}` executed successfully")
        else:
            st.error(f"Failed: {result.get('error', 'Unknown error')}")

        st.json(result)
    else:
        st.error(f"Skill `{selected}` not found in registry")

st.divider()

# ── AutoSkill Generator ─────────────────────────────────────────────────────
st.markdown("### 🧬 AutoSkill Generator")
st.markdown("Generate a new skill from a natural language description.")

gap_desc = st.text_input("What capability does the agent need?",
                         placeholder="Calculate profit margin for a sales order")
gap_domain = st.selectbox("Domain", ["sales", "production", "purchasing", "person", "cross-domain"], key="gap_domain")

if st.button("🧬 Generate Skill", use_container_width=True) and gap_desc:
    from agent.autoskill.loop import handle_gap

    with st.spinner("Generating skill with Claude..."):
        result = run_async(handle_gap(
            user_message=gap_desc,
            gap_description=gap_desc,
            domain=gap_domain,
            registry=registry,
            max_attempts=3,
        ))

    if result.get("success"):
        st.success(f"Skill **`{result['skill_name']}`** generated and registered!")
        st.markdown(f"- **Description:** {result['description']}")
        st.markdown(f"- **Domain:** {result['domain']}")
        st.markdown(f"- **Code:** `{result['code_path']}`")
        st.markdown(f"- **Attempts:** {result['attempts']}")
        st.balloons()
    else:
        st.error(f"Generation failed: {result.get('reason', 'Unknown')}")
