"""Skills — registry browser, executor, and AutoSkill generator."""

import streamlit as st
from interfaces.dashboard.helpers import inject_css, run_async, COLORS

st.set_page_config(page_title="SpineAgent — Skills", page_icon="🧠", layout="wide")
inject_css()

st.markdown("### Skill Registry")
st.caption("All capabilities the agent can execute — including AI-generated skills.")

# ── Load skills ──────────────────────────────────────────────────────────────
from skills.registry import SkillRegistry

registry = SkillRegistry()
run_async(registry.ensure_builtin_skills())
all_skills = run_async(registry.list_all())

# ── KPIs ─────────────────────────────────────────────────────────────────────
domains = sorted(set(s["domain"] for s in all_skills))
total_usage = sum(s.get("usage_count", 0) for s in all_skills)

k1, k2, k3 = st.columns(3)
k1.metric("Total Skills", len(all_skills))
k2.metric("Domains", len(domains))
k3.metric("Total Executions", total_usage)

st.divider()

# ── Skill catalog ────────────────────────────────────────────────────────────
st.markdown("**Skill Catalog**")

domain_colors = {
    "sales": COLORS["primary"],
    "production": COLORS["success"],
    "purchasing": COLORS["warning"],
    "person": "#a78bfa",
    "cross-domain": COLORS["text_dim"],
}

for domain in domains:
    domain_skills = [s for s in all_skills if s["domain"] == domain]
    color = domain_colors.get(domain, COLORS["text_dim"])

    with st.expander(f"{domain.title()} — {len(domain_skills)} skill(s)", expanded=True):
        for skill in domain_skills:
            trigger = skill.get("trigger_type", "on_demand")
            trigger_label = {"auto_generated": "AutoGenerated", "persistent": "Persistent"}.get(trigger, "On Demand")
            trigger_color = COLORS["success"] if trigger == "auto_generated" else COLORS["text_dim"]

            st.markdown(
                f'<div style="display:flex;justify-content:space-between;align-items:center;'
                f'padding:10px 0;border-bottom:1px solid {COLORS["border"]}">'
                f'<div>'
                f'<span style="color:{COLORS["text"]};font-weight:600;font-size:0.9rem">{skill["name"]}</span>'
                f'<br><span style="color:{COLORS["text_muted"]};font-size:0.8rem">{skill["description"]}</span>'
                f'</div>'
                f'<div style="text-align:right">'
                f'<span style="color:{COLORS["text_dim"]};font-size:0.75rem">Used {skill.get("usage_count", 0)}x</span>'
                f'<br><span style="color:{trigger_color};font-size:0.7rem;background:{trigger_color}22;'
                f'padding:2px 8px;border-radius:8px">{trigger_label}</span>'
                f'</div></div>',
                unsafe_allow_html=True,
            )

st.divider()

# ── Skill Executor ───────────────────────────────────────────────────────────
st.markdown("**Skill Executor**")
st.caption("Run any skill directly with custom parameters.")

skill_names = [s["name"] for s in all_skills]
col_sel, col_oid, col_pid, col_run = st.columns([3, 2, 2, 1])
selected = col_sel.selectbox("Skill", skill_names, label_visibility="collapsed")
order_id = col_oid.number_input("order_id", min_value=1, value=43659, step=1)
product_id = col_pid.number_input("product_id", min_value=0, value=0, step=1)
col_run.markdown("")
execute_btn = col_run.button("Run", use_container_width=True, type="primary")

if execute_btn:
    skill = run_async(registry.get(selected))
    if skill:
        params = {"order_id": int(order_id)}
        if product_id > 0:
            params["product_id"] = int(product_id)

        with st.spinner(""):
            try:
                result = run_async(skill.execute(**params))
                run_async(registry.record_usage(selected))
            except Exception as e:
                result = {"success": False, "error": str(e)}

        if result.get("success"):
            st.success(f"`{selected}` executed successfully")
        else:
            st.error(f"Failed: {result.get('error', 'Unknown error')}")
        st.json(result)

st.divider()

# ── AutoSkill Generator ─────────────────────────────────────────────────────
st.markdown("**AutoSkill Generator**")
st.caption("Describe a capability the agent needs — Claude will generate a new skill.")

st.markdown(
    f'<div class="card card-accent-green" style="padding:14px 20px">'
    f'<div class="feature-desc" style="max-width:100%">'
    f'When the agent encounters a request it can\'t handle, the AutoSkill loop activates: '
    f'it detects the gap, generates Python code with Claude, validates it in a sandbox, '
    f'and persists it in the registry. Try it below.'
    f'</div></div>',
    unsafe_allow_html=True,
)

col_desc, col_domain = st.columns([3, 1])
gap_desc = col_desc.text_input("Capability needed", placeholder="Calculate profit margin for a sales order")
gap_domain = col_domain.selectbox("Domain", ["sales", "production", "purchasing", "person", "cross-domain"], key="gap_d")

if st.button("Generate Skill", use_container_width=True, type="primary") and gap_desc:
    from agent.autoskill.loop import handle_gap

    with st.spinner("Generating with Claude..."):
        result = run_async(handle_gap(
            user_message=gap_desc,
            gap_description=gap_desc,
            domain=gap_domain,
            registry=registry,
            max_attempts=3,
        ))

    if result.get("success"):
        st.success(f"Skill **{result['skill_name']}** generated and registered!")
        st.markdown(
            f'<div class="card card-accent-green">'
            f'<div style="font-size:0.85rem;color:{COLORS["text_muted"]}">'
            f'<strong>Name:</strong> {result["skill_name"]}<br>'
            f'<strong>Description:</strong> {result["description"]}<br>'
            f'<strong>Domain:</strong> {result["domain"]}<br>'
            f'<strong>Code:</strong> {result["code_path"]}<br>'
            f'<strong>Attempts:</strong> {result["attempts"]}'
            f'</div></div>',
            unsafe_allow_html=True,
        )
        st.balloons()
    else:
        st.error(f"Generation failed: {result.get('reason', 'Unknown')}")
