"""AutoSkill Validator — validates generated skills in a sandbox before registration.

Checks:
  1. Code compiles (no syntax errors)
  2. Generated class subclasses BaseSkill
  3. Has required attributes (name, description, domain)
  4. execute() is callable
  5. (Optional) dry-run execution to test it actually works
"""

from __future__ import annotations

import importlib
import sys
import types
from pathlib import Path

from skills.base_skill import BaseSkill


class ValidationResult:
    """Result of validating a generated skill."""

    def __init__(self, valid: bool, skill: BaseSkill | None = None, error: str | None = None):
        self.valid = valid
        self.skill = skill
        self.error = error

    def __repr__(self) -> str:
        if self.valid:
            return f"ValidationResult(valid=True, skill={self.skill.name!r})"
        return f"ValidationResult(valid=False, error={self.error!r})"


def validate_skill_code(name: str, code: str) -> ValidationResult:
    """Validate generated skill code without executing it.

    Compiles the code, loads it as a module, and checks that it defines
    a proper BaseSkill subclass.
    """
    # 1. Compile check
    try:
        compiled = compile(code, f"<autoskill:{name}>", "exec")
    except SyntaxError as exc:
        return ValidationResult(valid=False, error=f"Syntax error: {exc}")

    # 2. Execute in isolated namespace
    module = types.ModuleType(f"autoskill_{name}")
    module.__dict__["__builtins__"] = __builtins__

    # Inject required imports so the generated code can resolve them
    sys.modules[f"autoskill_{name}"] = module
    try:
        exec(compiled, module.__dict__)
    except Exception as exc:
        return ValidationResult(valid=False, error=f"Execution error: {exc}")
    finally:
        sys.modules.pop(f"autoskill_{name}", None)

    # 3. Find the BaseSkill subclass
    skill_class = None
    for attr_name in dir(module):
        attr = getattr(module, attr_name)
        if (
            isinstance(attr, type)
            and issubclass(attr, BaseSkill)
            and attr is not BaseSkill
        ):
            skill_class = attr
            break

    if skill_class is None:
        return ValidationResult(valid=False, error="No BaseSkill subclass found in generated code")

    # 4. Check required attributes
    try:
        instance = skill_class()
    except Exception as exc:
        return ValidationResult(valid=False, error=f"Cannot instantiate: {exc}")

    if not hasattr(instance, "name") or not instance.name:
        return ValidationResult(valid=False, error="Skill missing 'name' attribute")
    if not hasattr(instance, "description") or not instance.description:
        return ValidationResult(valid=False, error="Skill missing 'description' attribute")
    if not hasattr(instance, "domain") or not instance.domain:
        return ValidationResult(valid=False, error="Skill missing 'domain' attribute")
    if not callable(getattr(instance, "execute", None)):
        return ValidationResult(valid=False, error="Skill missing 'execute' method")

    return ValidationResult(valid=True, skill=instance)


def persist_skill_code(name: str, code: str) -> Path:
    """Write generated skill code to the autogenerated skills directory.

    Returns the path to the written file.
    """
    autogen_dir = Path("skills/autogenerated")
    autogen_dir.mkdir(parents=True, exist_ok=True)

    # Write __init__.py if it doesn't exist
    init_file = autogen_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("")

    file_path = autogen_dir / f"{name}.py"
    file_path.write_text(code)
    return file_path
